from definitions import IMAGES_DIR
import os


proj_defs = {
    "toscana": {
        "projection": "merc",
        "llcrnrlon": 9.6,
        "llcrnrlat": 42.2,
        "urcrnrlon": 12.4,
        "urcrnrlat": 44.5,
        "resolution": "h",
        "epsg": 3857,
    },
    "nord": {
        "projection": "merc",
        "llcrnrlon": 5.,
        "llcrnrlat": 43.5,
        "urcrnrlon": 14.5,
        "urcrnrlat": 47.7,
        "resolution": "h",
        "epsg": 3857,
    },
    "centro": {
        "projection": "merc",
        "llcrnrlon": 9.8,
        "llcrnrlat": 40.9,
        "urcrnrlon": 15.2,
        "urcrnrlat": 44.1,
        "resolution": "h",
        "epsg": 3857,
    },
    "sud": {
        "projection": "merc",
        "llcrnrlon": 11.8,
        "llcrnrlat": 36.5,
        "urcrnrlon": 18.6,
        "urcrnrlat": 42.0,
        "resolution": "h",
        "epsg": 3857,
    },
    "it": {
        "projection": "merc",
        "llcrnrlon": 5,
        "llcrnrlat": 36,
        "urcrnrlon": 19,
        "urcrnrlat": 47.7,
        "resolution": "i",
        "epsg": 3857,
    },
    "piemonte": {
        "projection": "merc",
        "llcrnrlon": 6.5,
        "llcrnrlat": 44.0,
        "urcrnrlon": 9.3,
        "urcrnrlat": 46.5,
        "resolution": "h",
        "epsg": 3857,
    },
    "lombardia": {
        "projection": "merc",
        "llcrnrlon": 8.45,
        "llcrnrlat": 44.6,
        "urcrnrlon": 11.45,
        "urcrnrlat": 46.7,
        "resolution": "h",
        "epsg": 3857,
    },
    "veneto": {
        "projection": "merc",
        "llcrnrlon": 10.62,
        "llcrnrlat": 44.79,
        "urcrnrlon": 13.1,
        "urcrnrlat": 46.7,
        "resolution": "h",
        "epsg": 3857,
    },
    "liguria": {
        "projection": "merc",
        "llcrnrlon": 7.4,
        "llcrnrlat": 43.7,
        "urcrnrlon": 10.1,
        "urcrnrlat": 44.7,
        "resolution": "h",
        "epsg": 3857,
    },
    "emilia_romagna": {
        "projection": "merc",
        "llcrnrlon": 9.0,
        "llcrnrlat": 43.65,
        "urcrnrlon": 12.8,
        "urcrnrlat": 45.25,
        "resolution": "h",
        "epsg": 3857,
    },
    "lazio": {
        "projection": "merc",
        "llcrnrlon": 11.8,
        "llcrnrlat": 41.15,
        "urcrnrlon": 14.1,
        "urcrnrlat": 42.9,
        "resolution": "h",
        "epsg": 3857,
    },
    "campania": {
        "projection": "merc",
        "llcrnrlon": 13.7,
        "llcrnrlat": 39.8,
        "urcrnrlon": 15.8,
        "urcrnrlat": 41.6,
        "resolution": "h",
        "epsg": 3857,
    },
    "sicilia": {
        "projection": "merc",
        "llcrnrlon": 11.8,
        "llcrnrlat": 36.4,
        "urcrnrlon": 15.7,
        "urcrnrlat": 38.8,
        "resolution": "h",
        "epsg": 3857,
    },
    "sardegna": {
        "projection": "merc",
        "llcrnrlon": 8.1,
        "llcrnrlat": 38.8,
        "urcrnrlon": 9.9,
        "urcrnrlat": 41.4,
        "resolution": "h",
        "epsg": 3857,
    },
    "puglia": {
        "projection": "merc",
        "llcrnrlon": 14.9,
        "llcrnrlat": 39.8,
        "urcrnrlon": 18.5,
        "urcrnrlat": 42.2,
        "resolution": "h",
        "epsg": 3857,
    },
    "calabria": {
        "projection": "merc",
        "llcrnrlon": 15.3,
        "llcrnrlat": 37.8,
        "urcrnrlon": 17.3,
        "urcrnrlat": 40.2,
        "resolution": "h",
        "epsg": 3857,
    },
    "friuli_venezia_giulia": {
        "projection": "merc",
        "llcrnrlon": 12.32,
        "llcrnrlat": 45.6,
        "urcrnrlon": 13.9,
        "urcrnrlat": 46.65,
        "resolution": "h",
        "epsg": 3857,
    },
    "umbria": {
        "projection": "merc",
        "llcrnrlon": 11.7,
        "llcrnrlat": 42.3,
        "urcrnrlon": 13.3,
        "urcrnrlat": 43.65,
        "resolution": "h",
        "epsg": 3857,
    },
    "marche": {
        "projection": "merc",
        "llcrnrlon": 12.2,
        "llcrnrlat": 42.7,
        "urcrnrlon": 14.1,
        "urcrnrlat": 44.1,
        "resolution": "h",
        "epsg": 3857,
    },
    "abruzzo": {
        "projection": "merc",
        "llcrnrlon": 12.9,
        "llcrnrlat": 41.6,
        "urcrnrlon": 14.7,
        "urcrnrlat": 42.9,
        "resolution": "h",
        "epsg": 3857,
    },
    "basilicata": {
        "projection": "merc",
        "llcrnrlon": 15.5,
        "llcrnrlat": 39.7,
        "urcrnrlon": 16.9,
        "urcrnrlat": 40.7,
        "resolution": "h",
        "epsg": 3857,
    },
    "molise": {
        "projection": "merc",
        "llcrnrlon": 13.8,
        "llcrnrlat": 41.4,
        "urcrnrlon": 15.1,
        "urcrnrlat": 42.1,
        "resolution": "h",
        "epsg": 3857,
    },
    "trentino_alto_adige": {
        "projection": "merc",
        "llcrnrlon": 10.3,
        "llcrnrlat": 45.7,
        "urcrnrlon": 12.4,
        "urcrnrlat": 47.1,
        "resolution": "h",
        "epsg": 3857,
    },
    "valle_d_aosta": {
        "projection": "merc",
        "llcrnrlon": 6.9,
        "llcrnrlat": 45.6,
        "urcrnrlon": 7.9,
        "urcrnrlat": 46.5,
        "resolution": "h",
        "epsg": 3857,
    }
}


# Dictionary to map the output folder based on the projection employed
subfolder_images = {}
for proj in proj_defs:
    subfolder_images[proj] = os.path.join(IMAGES_DIR, proj)
